### ISSUE TITLE
Updated TD logo in footer

### ISSUE THREAD

**Issue by attentioneering** [hypenotic/park-grants-en#16]
Please update the footer component on the EN TD Grants page (https://parkpeople.ca/parkgrants/) to use the following lockup:

EN:
![TDReadyCommitment_LockupEN](https://user-images.githubusercontent.com/46387723/73382264-3251bf80-4295-11ea-8dc3-47961069229f.png)

Some minor padding changes may be required.
Here's what the old one looks like:
<img width="1096" alt="Screen Shot 2020-01-29 at 12 43 56" src="https://user-images.githubusercontent.com/46387723/73382282-38e03700-4295-11ea-8531-537119da5781.png">

**Comment by hubret** [comment]
ae3ab66
