### ISSUE TITLE
TD Grants: Search box

### ISSUE THREAD

**Issue by attentioneering** [hypenotic/park-grants-en#19]
Hi Hubert!
Clemence has also asked if we can look into the position/function of this search box on the TD Grants map.<img width="1060" alt="Screen Shot 2020-05-13 at 20 17 05" src="https://user-images.githubusercontent.com/46387723/81878676-b8e59080-9556-11ea-9b06-b4542100dab0.png">
It covers the events on the map and goes to the middle of the pacific ocean when you search. Not very helpful. 
The search/recenter map functionality works correctly for the regular listings map (https://parkpeople.ca/listings/).
If it can't be fixed for some reason, perhaps the search box can be moved to the top or bottom of the map box.

**Comment by attentioneering** [comment]
Low priority as maps will be reworked later this year.

**Comment by lionelmann** [comment]
This is being redone in a new project. Closing
