### ISSUE TITLE
Event form updates

### ISSUE THREAD

**Issue by attentioneering** [hypenotic/park-grants-en#23]
Hi both!
Not sure who's gonna take this on, but we need to make some changes to the event intake form on the dashboard. Pretty sure it's hard coded.
Here's what we need:

1. Make the Full Address field mandatory (it determines pin placement for the maps)
2. Update the tooltip for Full Address to the following: 

- EN "Street address only- this info is necessary to plot your event on the map"
- FR "Adresse postale seulement - cette information est nécessaire pour tracer votre événement sur la carte"

Please let me know if you need any help!
Cheers,

Cat.

**Comment by hubret** [comment]
all dashboard related issues should go on the parkpeople repo

**Comment by hubret** [comment]
https://github.com/hypenotic/parkpeople/issues/114
